### ISSUE TITLE
Actor invocations should clean up after themselves

### ISSUE THREAD

**Issue by deardooley** [TACC/abaco#12]
Currently when invoking actors repeatedly, the completed containers are left on the execution host. This creates a heck of a stockpile of containers and disk. Having them cleaned up after completion would help the system stay up longer, achieve better throughput, and handle requests for larger containers more promptly.

**Comment by joestubbs** [comment]
Yes, this is actually fixed in the current version but not deployed to staging yet.

**Comment by deardooley** [comment]
How is it configured? I’m running from the repo.

—
Rion

**Comment by joestubbs** [comment]
Hmm, there's no configuration needed. You are seeing actor containers pile up? If so, that's a bug. The commit was from October: 61407c8d326e856b59059c5b79bcdac0c736f264

**Comment by joestubbs** [comment]
Pushed a fix. Docker 1.9 broke the stats API since there are multiple networks now, a network must be selected. Since stats collection happens before removal, it was breaking container removal as well. Two of the automated tests are still failing, so I am continuing to look, but manual testing appears to be working.

**Comment by joestubbs** [comment]
Test are now passing and staging has been updated. Closing out.
